apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: db-secret
  namespace: default
data:
  DBUSER: Y29tcGxldGVfcG9zdGdyZXNxbAo=
  DBPASS: WW91clB3ZFNob3VsZEJlTG9uZ0FuZFNlY3VyZSEK
  DBHOST: b2xpZW4uY29sYmV3eHpxN2p2LnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQo=
  DBNAME: Y29tcGxldGVQb3N0Z3Jlc3FsCg==

